# fly.toml file generated for audiophile-sidekiq-stg on 2022-12-10T21:05:51-05:00

app = "audiophile-sidekiq-stg"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "./Dockerfile.sidekiq.staging"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = "bundle exec rails db:migrate"
