json.uuid purchase_cart_item.uuid
json.stock_uuid purchase_cart_item.stock.uuid
json.quantity purchase_cart_item.quantity
json.unit_price purchase_cart_item.unit_price
json.price purchase_cart_item.total_price
