name: Rubocop Check
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: RuboCop Linter Action
        uses: andrewmcodes-archive/rubocop-linter-action@v3.3.0
